apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microclimate-data
  namespace: microclimate
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ibmc-file-bronze 