apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-data
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-file-bronze 