apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chartmuseum-data
  namespace: chartmuseum
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ibmc-file-bronze 