kind: Pod
apiVersion: v1
metadata:
  generateName: icp-mongodb-
  annotations:
    cni.projectcalico.org/podIP: 172.30.114.147/32
    cni.projectcalico.org/podIPs: 172.30.114.147/32
    prometheus.io/path: /metrics
    prometheus.io/port: '9216'
    prometheus.io/scrape: 'true'
  selfLink: /api/v1/namespaces/kube-system/pods/icp-mongodb-0
  resourceVersion: '249725'
  name: icp-mongodb-0
  uid: 0f276f07-fb89-4738-9e6f-bd56c93d3bbf
  creationTimestamp: '2020-03-16T20:03:08Z'
  namespace: kube-system
  ownerReferences:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: icp-mongodb
      uid: 555cd933-93e1-4ecc-a815-0dda85e327f7
      controller: true
      blockOwnerDeletion: true
  labels:
    app: icp-mongodb
    controller-revision-hash: icp-mongodb-6c9c8c9996
    release: mongodb
    statefulset.kubernetes.io/pod-name: icp-mongodb-0
spec:
  nodeSelector:
    master: 'true'
  restartPolicy: Always
  initContainers:
    - resources:
        limits:
          memory: 8Gi
        requests:
          memory: 4Gi
      terminationMessagePath: /dev/termination-log
      name: install
      command:
        - /install/install.sh
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mongodbdir
          mountPath: /work-dir
          subPath: workdir
        - name: configdir
          mountPath: /data/configdb
        - name: config
          mountPath: /configdb-readonly
        - name: install
          mountPath: /install
        - name: keydir
          mountPath: /keydir-readonly
        - name: ca
          mountPath: /ca-readonly
        - name: mongodbdir
          mountPath: /data/db
          subPath: datadir
        - name: tmp-mongodb
          mountPath: /tmp
        - name: default-token-42pn8
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb-install:3.3.1
      args:
        - '--work-dir=/work-dir'
        - '--config-dir=/data/configdb'
    - resources:
        limits:
          memory: 256Mi
        requests:
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      name: install-metrics
      command:
        - /bin/sh
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: tmp-metrics
          mountPath: /tmp
        - name: default-token-42pn8
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb-install:3.3.1
      args:
        - '-c'
        - chmod -R 777 /tmp
    - resources:
        limits:
          memory: 8Gi
        requests:
          memory: 4Gi
      terminationMessagePath: /dev/termination-log
      name: bootstrap
      command:
        - /work-dir/peer-finder
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: REPLICA_SET
          value: rs0
        - name: AUTH
          value: 'true'
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: icp-mongodb-admin
              key: user
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: icp-mongodb-admin
              key: password
        - name: METRICS
          value: 'true'
        - name: METRICS_USER
          valueFrom:
            secretKeyRef:
              name: icp-mongodb-metrics
              key: user
        - name: METRICS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: icp-mongodb-metrics
              key: password
        - name: NETWORK_IP_VERSION
          value: ipv4
      securityContext:
        runAsUser: 999
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mongodbdir
          mountPath: /work-dir
          subPath: workdir
        - name: configdir
          mountPath: /data/configdb
        - name: init
          mountPath: /init
        - name: mongodbdir
          mountPath: /data/db
          subPath: datadir
        - name: tmp-mongodb
          mountPath: /tmp
        - name: default-token-42pn8
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb:4.0.12-build.2
      args:
        - '-on-start=/init/on-start.sh'
        - '-service=icp-mongodb'
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-2d2bp
  priority: 2000000000
  subdomain: icp-mongodb
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  nodeName: 10.209.172.18
  securityContext: {}
  containers:
    - resources:
        limits:
          memory: 8Gi
        requests:
          memory: 4Gi
      readinessProbe:
        exec:
          command:
            - mongo
            - '--ssl'
            - '--sslCAFile=/data/configdb/tls.crt'
            - '--sslPEMKeyFile=/work-dir/mongo.pem'
            - '--eval'
            - db.adminCommand('ping')
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      name: icp-mongodb
      command:
        - mongod
        - '--config=/data/configdb/mongod.conf'
      livenessProbe:
        exec:
          command:
            - mongo
            - '--ssl'
            - '--sslCAFile=/data/configdb/tls.crt'
            - '--sslPEMKeyFile=/work-dir/mongo.pem'
            - '--eval'
            - db.adminCommand('ping')
        initialDelaySeconds: 30
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      env:
        - name: AUTH
          value: 'true'
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: icp-mongodb-admin
              key: user
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: icp-mongodb-admin
              key: password
      securityContext:
        runAsUser: 999
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      ports:
        - name: peer
          containerPort: 27017
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mongodbdir
          mountPath: /data/db
          subPath: datadir
        - name: configdir
          mountPath: /data/configdb
        - name: mongodbdir
          mountPath: /work-dir
          subPath: workdir
        - name: tmp-mongodb
          mountPath: /tmp
        - name: default-token-42pn8
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb:4.0.12-build.2
    - resources:
        limits:
          memory: 256Mi
        requests:
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      name: metrics
      command:
        - sh
        - '-ec'
        - >-
          /bin/mongodb_exporter --mongodb.uri
          mongodb://$METRICS_USER:$METRICS_PASSWORD@localhost:27017
          --mongodb.tls --mongodb.tls-ca=/data/configdb/tls.crt
          --mongodb.tls-cert=/work-dir/mongo.pem --mongodb.socket-timeout=3s
          --mongodb.sync-timeout=1m --web.telemetry-path=/metrics
          --web.listen-address=:9216
      livenessProbe:
        exec:
          command:
            - sh
            - '-ec'
            - >-
              /bin/mongodb_exporter --mongodb.uri
              mongodb://$METRICS_USER:$METRICS_PASSWORD@localhost:27017
              --mongodb.tls --mongodb.tls-ca=/data/configdb/tls.crt
              --mongodb.tls-cert=/work-dir/mongo.pem --test
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      env:
        - name: METRICS_USER
          valueFrom:
            secretKeyRef:
              name: icp-mongodb-metrics
              key: user
        - name: METRICS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: icp-mongodb-metrics
              key: password
      securityContext:
        runAsUser: 999
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      ports:
        - name: metrics
          containerPort: 9216
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: configdir
          mountPath: /data/configdb
        - name: mongodbdir
          mountPath: /work-dir
          subPath: workdir
        - name: tmp-metrics
          mountPath: /tmp
        - name: default-token-42pn8
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb-exporter:3.3.1
  hostname: icp-mongodb-0
  serviceAccount: default
  volumes:
    - name: mongodbdir
      persistentVolumeClaim:
        claimName: mongodbdir-icp-mongodb-0
    - name: config
      configMap:
        name: icp-mongodb
        defaultMode: 420
    - name: init
      configMap:
        name: icp-mongodb-init
        defaultMode: 493
    - name: install
      configMap:
        name: icp-mongodb-install
        defaultMode: 493
    - name: ca
      secret:
        secretName: cluster-ca-cert
        defaultMode: 256
    - name: keydir
      secret:
        secretName: icp-mongodb-keyfile
        defaultMode: 256
    - name: configdir
      emptyDir: {}
    - name: tmp-mongodb
      emptyDir: {}
    - name: tmp-metrics
      emptyDir: {}
    - name: default-token-42pn8
      secret:
        secretName: default-token-42pn8
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: dedicated
      operator: Exists
      effect: NoSchedule
    - key: CriticalAddonsOnly
      operator: Exists
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
  priorityClassName: system-cluster-critical
status:
  containerStatuses:
    - restartCount: 23
      started: false
      ready: false
      name: icp-mongodb
      state:
        waiting:
          reason: CrashLoopBackOff
          message: >-
            back-off 5m0s restarting failed container=icp-mongodb
            pod=icp-mongodb-0_kube-system(0f276f07-fb89-4738-9e6f-bd56c93d3bbf)
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb@sha256:cd4bca5af521299c0e12d6c2584a09cddafe927031ff16e4a52d08f959681fec
      image: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb:4.0.12-build.2
      lastState:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2020-03-16T21:16:38Z'
          finishedAt: '2020-03-16T21:17:55Z'
          containerID: >-
            cri-o://8876db7b4aa7964fcfb3bba809b56b67046f65631abe6de42697e9022752de09
      containerID: 'cri-o://8876db7b4aa7964fcfb3bba809b56b67046f65631abe6de42697e9022752de09'
    - restartCount: 24
      started: true
      ready: true
      name: metrics
      state:
        running:
          startedAt: '2020-03-16T21:21:45Z'
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb-exporter@sha256:54c4d0d2bd346dcb95b84561bedec7194c6916cacdf4a2af78bd00dbdab76b7e
      image: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb-exporter:3.3.1
      lastState:
        terminated:
          exitCode: 2
          reason: Error
          startedAt: '2020-03-16T21:15:37Z'
          finishedAt: '2020-03-16T21:16:38Z'
          containerID: >-
            cri-o://ce1e4ba9ba3bcf71157214b6bef09ffe6f1d2fc192799d9c4f49aa372cb3520c
      containerID: 'cri-o://ff2c1f0bce69f857c14917ecf77deae031a6b6c0801fdad23ed63ab72527033f'
  qosClass: Burstable
  podIPs:
    - ip: 172.30.114.147
  podIP: 172.30.114.147
  hostIP: 10.209.172.18
  startTime: '2020-03-16T20:05:08Z'
  initContainerStatuses:
    - name: install
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2020-03-16T20:05:28Z'
          finishedAt: '2020-03-16T20:05:29Z'
          containerID: >-
            cri-o://ce26c4a51b6c0eb5338914e18b40a72a7e8122d9d82be6b2ee3d0aead5ddad27
      lastState: {}
      ready: true
      restartCount: 0
      image: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb-install:3.3.1
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb-install@sha256:a310f2db592ac56c250e033a1fe7b67430931dcd20abe75f5fcfe09eb5abdae0
      containerID: 'cri-o://ce26c4a51b6c0eb5338914e18b40a72a7e8122d9d82be6b2ee3d0aead5ddad27'
    - name: install-metrics
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2020-03-16T20:05:30Z'
          finishedAt: '2020-03-16T20:05:30Z'
          containerID: >-
            cri-o://9674fc8affa2a81358f5ae1ab63ef8bad109754293f08de07e2c1b26891b3753
      lastState: {}
      ready: true
      restartCount: 0
      image: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb-install:3.3.1
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb-install@sha256:a310f2db592ac56c250e033a1fe7b67430931dcd20abe75f5fcfe09eb5abdae0
      containerID: 'cri-o://9674fc8affa2a81358f5ae1ab63ef8bad109754293f08de07e2c1b26891b3753'
    - name: bootstrap
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2020-03-16T20:05:46Z'
          finishedAt: '2020-03-16T20:07:20Z'
          containerID: >-
            cri-o://8fc67657343bd40b0cfba85e294280557112d8f88692bf1cb7c0fefa4196938f
      lastState: {}
      ready: true
      restartCount: 0
      image: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb:4.0.12-build.2
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/ibmcom/ibm-mongodb@sha256:cd4bca5af521299c0e12d6c2584a09cddafe927031ff16e4a52d08f959681fec
      containerID: 'cri-o://8fc67657343bd40b0cfba85e294280557112d8f88692bf1cb7c0fefa4196938f'
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-03-16T20:07:21Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2020-03-16T20:05:08Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [icp-mongodb]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2020-03-16T20:05:08Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [icp-mongodb]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-03-16T20:05:08Z'
  phase: Running
