kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    ibm.io/provisioning-status: complete
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-file
  selfLink: >-
    /api/v1/namespaces/kube-system/persistentvolumeclaims/mongodbdir-icp-mongodb-1
  resourceVersion: '1000782'
  name: mongodbdir-icp-mongodb-0
  uid: eb0a11b0-36aa-4268-a54a-31ba385949e2
  creationTimestamp: '2020-03-18T19:18:50Z'
  namespace: kube-system
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: icp-mongodb
    region: us-south
    release: mongodb
    zone: dal13
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pvc-b703d53d-23b4-414e-a19d-9df58d3b827d
  storageClassName: ibmc-file-retain-bronze
  volumeMode: Filesystem
status:
  phase: Lost
