apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "chown -R 1000:1000 /var/jenkins_home"]
        volumeMounts:
            - name: jenkins-persistent-storage
              mountPath: /var/jenkins_home 
      containers:
      - name: jenkins
        image: jenkins/jenkins
        ports:
        - containerPort: 8080
        volumeMounts:
              - name: jenkins-persistent-storage
                mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-persistent-storage
        persistentVolumeClaim:
           claimName: jenkins-data