apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  initContainers:
    - name: volume-mount-hack
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "rm -fr /var/jenkins_home/*"]
      volumeMounts:
        - name: jenkins-persistent-storage
          mountPath: /var/jenkins_home 
  containers:
    - name:  ubuntu
      image: ubuntu:14.04
      args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 100; done']  
      volumeMounts:
         - name: jenkins-persistent-storage
           mountPath: /var/jenkins_home
  volumes:
     - name: jenkins-persistent-storage
       persistentVolumeClaim:
         claimName: jenkins-data