kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    ibm.io/provisioning-status: complete
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-block
  selfLink: >-
    /api/v1/namespaces/kube-system/persistentvolumeclaims/exchange-db-claim-edge-computing-exchangedb-keeper-0
  resourceVersion: '855421'
  name: exchange-db-claim-edge-computing-exchangedb-keeper-0
  uid: 5fabfc48-6c64-4438-b3ca-060bd0298d65
  creationTimestamp: '2020-04-02T19:20:37Z'
  namespace: kube-system
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: edge-computing
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: exchangedb
    component: stolon-keeper
    helm.sh/chart: exchangedb
    region: us-south
    release: edge-computing
    zone: dal13
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-5fabfc48-6c64-4438-b3ca-060bd0298d65
  storageClassName: ibmc-block-gold
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
