kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvc-3434e84d-eb9a-418f-916c-ed67d24f9726
  selfLink: /api/v1/persistentvolumes/pvc-3434e84d-eb9a-418f-916c-ed67d24f9726
  uid: 377578d3-d808-4918-97a8-f3e25b1f2fdf
  resourceVersion: '855037'
  creationTimestamp: '2020-04-02T19:22:05Z'
  labels:
    CapacityGb: '20'
    Datacenter: dal13
    IOPS: '10'
    StorageType: Endurance
    billingType: hourly
    failure-domain.beta.kubernetes.io/region: us-south
    failure-domain.beta.kubernetes.io/zone: dal13
    ibm-cloud.kubernetes.io/iaas-provider: softlayer
  annotations:
    ibm.io/dm: /dev/dm-1
    ibm.io/mountpath: >-
      /var/data/kubelet/plugins/kubernetes.io/flexvolume/ibm/ibmc-block/mounts/pvc-3434e84d-eb9a-418f-916c-ed67d24f9726
    ibm.io/mountstatus: mounted
    ibm.io/network-storage-id: '133075290'
    ibm.io/nodename: 10.209.172.38
    pv.kubernetes.io/provisioned-by: ibm.io/ibmc-block
    volume.beta.kubernetes.io/storage-class: ''
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 20Gi
  flexVolume:
    driver: ibm/ibmc-block
    fsType: ext4
    options:
      Lun: '1'
      TargetPortal: 161.26.114.138
      VolumeID: '133075290'
      volumeName: pvc-3434e84d-eb9a-418f-916c-ed67d24f9726
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: kube-system
    name: agbot-db-claim-edge-computing-agbotdb-keeper-0
    uid: 3434e84d-eb9a-418f-916c-ed67d24f9726
    apiVersion: v1
    resourceVersion: '853814'
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ibmc-block-gold
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: failure-domain.beta.kubernetes.io/region
              operator: In
              values:
                - us-south
            - key: failure-domain.beta.kubernetes.io/zone
              operator: In
              values:
                - dal13
status:
  phase: Bound